name:                haskell-in-depth
version:             0.1.0.0
github:              "martinrist/haskell-in-depth"
license:             BSD3
author:              "Martin Rist"
maintainer:          "mlr-github@martinrist.com"
copyright:           "2019 Martin Rist"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martinrist/haskell-in-depth#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - text

executables:
  vocab1:
    main:                Main.hs
    source-dirs:         app/chapter02/vocab1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-depth
    - text

  vocab2:
    main:                Main.hs
    source-dirs:         app/chapter02/vocab2
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-in-depth
      - text

  vocab3:
    main:                Main.hs
    source-dirs:         app/chapter02/vocab3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-in-depth
      - text

tests:
  haskell-in-depth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-depth
